// <auto-generated />
using Cinema2026.Repo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema2026.Repo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260916194143_testmoviehall")]
    partial class testmoviehall
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema2026.Repo.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int?>("MovieHallId")
                        .HasColumnType("int");

                    b.Property<int>("Movieage")
                        .HasColumnType("int");

                    b.Property<string>("Moviename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("MovieHallId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.MovieHall", b =>
                {
                    b.Property<int>("MovieHallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieHallId"));

                    b.Property<bool>("MovieHalloccupied")
                        .HasColumnType("bit");

                    b.HasKey("MovieHallId");

                    b.ToTable("MovieHalls");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<int?>("MovieHallId")
                        .HasColumnType("int");

                    b.Property<int>("Personage")
                        .HasColumnType("int");

                    b.Property<string>("Personname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("MovieHallId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.Movie", b =>
                {
                    b.HasOne("Cinema2026.Repo.Models.MovieHall", null)
                        .WithMany("MoviesId")
                        .HasForeignKey("MovieHallId");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.Person", b =>
                {
                    b.HasOne("Cinema2026.Repo.Models.MovieHall", null)
                        .WithMany("PersonsId")
                        .HasForeignKey("MovieHallId");
                });

            modelBuilder.Entity("Cinema2026.Repo.Models.MovieHall", b =>
                {
                    b.Navigation("MoviesId");

                    b.Navigation("PersonsId");
                });
#pragma warning restore 612, 618
        }
    }
}
